# Packer template for the ai-playground base qcow2 image.
#
# Boots the Debian 13 (Trixie) generic cloud image as a KVM/QEMU VM,
# personalizes it with a NoCloud seed ISO (ssh pubkey for user `debian`),
# runs the default/custom provisioners over SSH, clears per-instance state,
# shuts down, and writes build/ai-playground-base/ai-playground-base
# (a qcow2 disk image usable directly by libvirt, Proxmox, AWS, etc.).

packer {
  required_plugins {
    qemu = {
      version = ">= 1.0.9"
      source  = "github.com/hashicorp/qemu"
    }
  }
}

variable "artifact_dir" {
  type        = string
  default     = "${env("ARTIFACT_DIR")}"
  description = "Output directory for artifacts (overridable via ARTIFACT_DIR env var)"
}

variable "vm_name" {
  type        = string
  default     = "ai-playground-base"
  description = "Name of the VM and resulting disk artifact"
}

# Pinned Debian cloud image snapshot. Bump snapshot_dir and image_filename
# together to upgrade the base. The filename mirrors the snapshot date
# because dated snapshots embed it (unlike the rolling `latest/` alias).
variable "debian_snapshot_dir" {
  type    = string
  default = "20260413-2447"
}

variable "debian_image_filename" {
  type    = string
  default = "debian-13-genericcloud-amd64-20260413-2447.qcow2"
}

locals {
  output_dir          = var.artifact_dir
  debian_snapshot_url = "https://cloud.debian.org/images/cloud/trixie/${var.debian_snapshot_dir}"
  debian_image_url    = "${local.debian_snapshot_url}/${var.debian_image_filename}"
  debian_checksum_url = "file:${local.debian_snapshot_url}/SHA512SUMS"
}

source "qemu" "debian13" {
  # Input: use the Debian cloud qcow2 directly as the boot disk.
  iso_url      = local.debian_image_url
  iso_checksum = local.debian_checksum_url
  disk_image   = true

  # VM hardware.
  # `memory` is build-time only (not a property of the resulting qcow2).
  # 6 GB is needed because the Debian cloud image ships without swap and the
  # Claude Code installer peak-RSS exceeds 4 GB; with no swap the OOM killer
  # (exit 137) terminates it.
  vm_name        = var.vm_name
  cpus           = 2
  memory         = 6144
  disk_size      = "20G"
  format         = "qcow2"
  accelerator    = "kvm"
  headless       = true
  net_device     = "virtio-net"
  disk_interface = "virtio"

  # Pass the host's CPU model through to the guest. qemu's default CPU model
  # omits AVX, and Claude Code (shipped as a Bun binary) requires AVX and
  # crashes with SIGILL (exit 132) otherwise.
  qemuargs = [
    ["-cpu", "host"],
  ]

  # NoCloud seed ISO — cloud-init reads the build-only SSH pubkey from here
  cd_files = [
    "${path.root}/seed/user-data",
    "${path.root}/seed/meta-data",
  ]
  cd_label = "cidata"

  # SSH — authenticate with the build-only keypair generated by
  # scripts/prepare-packer-seed.sh
  communicator           = "ssh"
  ssh_username           = "debian"
  ssh_private_key_file   = "${path.root}/seed/id_ed25519"
  ssh_timeout            = "10m"
  ssh_handshake_attempts = 100

  # Remove the build-only `debian` user (and its build-time SSH pubkey
  # under /home/debian/.ssh/authorized_keys) as the very last act, then
  # power off. The cleanup provisioner can't do this because once `debian`
  # is gone, subsequent sudo calls from the SSH session fail. Run
  # everything as root in one `sudo bash -c` so no further sudo is needed
  # after userdel. The cloud-init seed used by ai-playground at runtime
  # creates a fresh per-VM user, so the absence of `debian` is invisible
  # to consumers of the image.
  shutdown_command = "sudo bash -c 'userdel -rf debian 2>/dev/null; rm -rf /home/debian; poweroff'"
  shutdown_timeout = "5m"

  output_directory = "${local.output_dir}/packer-${var.vm_name}"
}

build {
  sources = ["source.qemu.debian13"]

  # Let cloud-init finish its first-boot work before we start apt installs
  # of our own — otherwise provisioners race against cloud-init's package
  # module and dpkg locks.
  provisioner "shell" {
    inline = ["sudo cloud-init status --wait"]
  }

  # Upload and run the numbered provisioning hooks
  provisioner "file" {
    source      = "${path.root}/run-provision.sh"
    destination = "/tmp/run-provision.sh"
  }

  provisioner "file" {
    source      = "${path.root}/default-provision"
    destination = "/tmp"
  }

  provisioner "file" {
    source      = "${path.root}/custom-provision"
    destination = "/tmp"
  }

  provisioner "shell" {
    inline = [
      "chmod +x /tmp/run-provision.sh",
      "/tmp/run-provision.sh /tmp",
      "rm -rf /tmp/default-provision /tmp/custom-provision /tmp/run-provision.sh"
    ]
  }

  # Apply chroot overlay
  provisioner "file" {
    source      = "${path.root}/../../chroot"
    destination = "/tmp"
  }

  provisioner "file" {
    source      = "${path.root}/../../scripts/provision-chroot.sh"
    destination = "/tmp/provision-chroot.sh"
  }

  provisioner "shell" {
    inline = [
      "chmod +x /tmp/provision-chroot.sh",
      "/tmp/provision-chroot.sh /tmp/chroot",
      "rm -rf /tmp/chroot /tmp/provision-chroot.sh"
    ]
  }

  # Poor-man's sysprep: strip per-instance state so the qcow2 is a reusable
  # golden image. Any clone's first boot will regenerate machine-id and SSH
  # host keys; cloud-init will re-run with the clone's own user-data.
  # (Upgrade path: install libguestfs and run `virt-sysprep` post-build.)
  provisioner "shell" {
    inline = [
      "sudo cloud-init clean --logs --seed",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo rm -f /var/lib/dbus/machine-id",
      "sudo rm -f /etc/ssh/ssh_host_*",
      "sudo rm -rf /var/log/*.log /var/log/*.gz /var/log/installer",
      "sudo rm -f /root/.bash_history /home/debian/.bash_history"
    ]
  }
}
